<a href="https://colab.research.google.com/github/soleildayana/Planetary-Sciences/blob/main/Movimientos_Sol_Tierra_Luna.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Cuaderno Primera Clase - Mecánica Celeste**
## **Ecuaciones del movimiento en el sistema Sol - Tierra - Luna**

*Soleil Dayana Niño Murcia (1033097666)*



# ***Resumen***

## Fuerza del Sol sobre la Tierra:
```
Vector fuerza (F_ST): [ 3.13813993e+22, -1.81327603e+22, 9.30789049e+17] Newtons.

Magnitud de la fuerza: 3.624347142707241e+22 Newtons.
```

## Fuerza del Sol sobre la Luna:

```
Vector fuerza (F_SL): [ 3.87493054e+20, -2.24322228e+20, -6.74322392e+15]
Newtons.
Magnitud de la fuerza: 4.477402473449021e+20 Newtons.
```
## Aceleración del Sol debida a la Tierra y la Luna

## ¿generalización N cuerpos?

## Aceleraciones netas (km/s²):


```
Sol: [-1.59770341e-08, 9.23204156e-09, -4.64715972e-13]
Tierra: [ 5.28800509e-03, -3.04302248e-03, 6.97077936e-07]
Luna: [ 2.56113152e-03, -2.50124588e-03, -4.41163256e-05]
```
## Fuerzas netas (N):
```
Sobre el Sol: [-3.17688924e+22, 1.83570826e+22, -9.24045825e+17]
Sobre la Tierra: [ 3.15808541e+22, -1.81734411e+22, 4.16306645e+18]
Sobre la Luna: [ 1.88038276e+20, -1.83641472e+20, -3.23902063e+18]
```

## Visualización del Sistema Sol-Tierra-Luna:

Se generó una gráfica interactiva en 3D utilizando plotly.graph_objects para mostrar la disposición espacial del Sol, la Tierra y la Luna el 2026-02-19 respecto al centro baricéntrico del sistema solar (SSB)
Estos cálculos nos permitieron analizar las interacciones gravitacionales en este sistema de tres cuerpos, desde las fuerzas individuales hasta las fuerzas netas que actúan sobre cada uno, culminando con una representación visual de su configuración.

# Apuntes

### Instalación de la librería `pymcel`

In [ ]:
!pip install -Uq pymcel

In [ ]:
import pymcel as pc
import matplotlib.pyplot as plt
import numpy as np
import spiceypy as spy

### Fuerza del Sol sobre la **Tierra**:

In [ ]:
m_tierra = pc.constantes.M_earth
m_sol = pc.constantes.M_sun
location, epoch = '@SSB', '2026-02-19'

In [ ]:
tabla, jd, X = pc.consulta_horizons(id = '399', location = location, epochs=epoch)
r_sol_Tierra = X[0:3]
r_sol_Tierra

array([-1.28447777e+11,  7.31597522e+10,  1.48918917e+07])



> Note que estamos tomando una fecha puntual, ¡el día de hoy!



# Reorganicemos esto...
Hasta aquí llegaban mis apuntes de clase. Conceptualmente aún no hemos calculado ninguna fuerza. Pero tenemos un vector posición respecto al SSB.

Y aquí viene algo importante: si queremos la fuerza del Sol sobre la Tierra, necesitamos el vector relativo Tierra–Sol, no el vector Tierra–SSB. Aunque obtengamos las posiciones respecto al SSB, la fuerza gravitacional entre dos cuerpos depende únicamente de su *separación relativa*.

## Fuerza Sol sobre la Tierra

In [ ]:
# Constantes y parámetros
G = pc.constantes.G
m_tierra = pc.constantes.M_earth
m_sol = pc.constantes.M_sun
mu_sol = G * m_sol

# Posiciones del Sol y la Tierra respecto al SSB
# Tierra
tabla_T, jd_T, X_T = pc.consulta_horizons(id='399', location='@SSB', epochs='2026-02-19')
r_T = X_T[0:3]

# Sol
tabla_S, jd_S, X_S = pc.consulta_horizons(id='10', location='@SSB', epochs='2026-02-19')
r_S = X_S[0:3]



>Nota técnica: en Horizons el Sol es id='10'


In [ ]:
# Vector relativo Sol-Tierra
r_ST = r_T - r_S
distancia = np.linalg.norm(r_ST)

# Fuerza Gravitacional
F_ST = -G * m_sol * m_tierra * r_ST / distancia**3

In [ ]:
F_mag = np.linalg.norm(F_ST)

print("Vector posición Sol → Tierra (km):")
print(r_ST)

print("\nDistancia Sol-Tierra (km):")
print(distancia)

print("\nMagnitud de la fuerza (N):")
print(F_mag)

print("\nVector fuerza del Sol sobre la Tierra (N):")
print(F_ST)

Vector posición Sol → Tierra (km):
[-1.28041114e+11  7.39845539e+10 -3.79776776e+06]

Distancia Sol-Tierra (km):
147879143406.5007

Magnitud de la fuerza (N):
3.624347142707241e+22

Vector fuerza del Sol sobre la Tierra (N):
[ 3.13813993e+22 -1.81327603e+22  9.30789049e+17]




> La componente en z es pequeña comparada con x e y, lo cual tiene sentido porque la órbita terrestre está casi en el plano eclíptico.



## Fuerza del Sol sobre la **Luna**

In [ ]:
tabla_L, jd_L, X_L = pc.consulta_horizons(id='301', location=location, epochs=epoch)
tabla_S, jd_S, X_S = pc.consulta_horizons(id='10', location=location, epochs=epoch)

r_L = X_L[0:3]
r_S = X_S[0:3]

Primero, definamos una función general para 2 cuerpos:

In [ ]:
def fuerza_gravitacional(m1, m2, r1, r2):
    r = r2 - r1
    d = np.linalg.norm(r)
    return -G * m1 * m2 * r / d**3

In [ ]:
F_ST = fuerza_gravitacional(m_sol, m_tierra, r_S, r_T)
print('Vector fuerza del Sol sobre la Tierra (N):')
print(F_ST)

Vector fuerza del Sol sobre la Tierra (N):
[ 3.13813993e+22 -1.81327603e+22  9.30789049e+17]




> La función general es consistente con el método previo. Doy visto bueno para aplicarlo al sistema Sol -> Luna


In [ ]:
tabla_L, jd_L, X_L = pc.consulta_horizons(id='301', location=location, epochs=epoch)
tabla_S, jd_S, X_S = pc.consulta_horizons(id='10', location=location, epochs=epoch)

r_L, r_S = X_L[0:3], X_S[0:3]



> Identificador NAIF de la Luna: '301'



In [ ]:
m_luna = 7.342e22 # no encontré el atributo de la luna para pymcel.constantes (no es la obvia M_moon)
print(f"Mass of the Moon (m_luna): {m_luna} kg")

Mass of the Moon (m_luna): 7.342e+22 kg


In [ ]:
F_SL = fuerza_gravitacional(m_sol, m_luna, r_S, r_L)
F_SL_mag = np.linalg.norm(F_SL)

print("Vector fuerza del Sol sobre la Luna (N):")
print(F_SL)
print("\nMagnitud de la fuerza del Sol sobre la Luna (N):")
print(F_SL_mag)

Vector fuerza del Sol sobre la Luna (N):
[ 3.87493054e+20 -2.24322228e+20 -6.74322392e+15]

Magnitud de la fuerza del Sol sobre la Luna (N):
4.477402473449021e+20


# ¡Fuerzas en el sistema de Sol - Tierra - Luna!

🌞 🌝 🌎

Es posible aplicar los métodos previos en sentido inverso, para estudiar las fuerzas que son ejercidas sobre el Sol. Pero qué tosco y aburrido... para hacerlo mucho más interesante:

 *¡estudiemos ya el sistema de los 3 cuerpos y las influencias netas sobre cada uno!*

In [ ]:
mu_T, mu_L = G * m_tierra , G * m_luna # Ya habíamos definido mu_sol

# Vectores relativos
r_ST = r_S - r_T
r_SL = r_S - r_L
r_TS = -r_ST
r_TL = r_T - r_L
r_LS = -r_SL
r_LT = -r_TL

### ☀ Aceleración del Sol debida a la Tierra y la Luna ☀

In [ ]:
# Tomamos fuerzas debidas tanto a Tierra como a Luna
a_S = (
    - mu_T * r_ST / np.linalg.norm(r_ST)**3
    - mu_L * r_SL / np.linalg.norm(r_SL)**3
)

### Función general para N cuerpos

In [ ]:
def aceleraciones_n_cuerpos(r, mu):
  N = len(r)
  a = np.zeros_like(r)

  for i in range(N):
      for j in range(N):
          if i != j:
              rij = r[i] - r[j]
              a[i] -= mu[j] * rij / np.linalg.norm(rij)**3

  return a

Para preparar los datos de la función `aceleraciones_n_cuerpos`, crearemos dos listas: una para los vectores de posición y otra para los parámetros gravitacionales, siguiendo el orden especificado de Sol, Tierra y Luna.


In [ ]:
r = [r_S, r_T, r_L]
mu = [mu_sol, mu_T, mu_L]

print("Lista de vectores de posición (Sol, Tierra, Luna):")
for i, pos in enumerate(r):
    print(f"  Cuerpo {i+1}: {pos}")

print("\nLista de parámetros gravitacionales (Sol, Tierra, Luna):")
for i, p_grav in enumerate(mu):
    print(f"  Cuerpo {i+1}: {p_grav}")

Lista de vectores de posición (Sol, Tierra, Luna):
  Cuerpo 1: [-4.06662772e+08 -8.24801720e+08  1.86896594e+07]
  Cuerpo 2: [-1.28447777e+11  7.31597522e+10  1.48918917e+07]
  Cuerpo 3: [-1.28076330e+11  7.30839921e+10  2.09113900e+07]

Lista de parámetros gravitacionales (Sol, Tierra, Luna):
  Cuerpo 1: 1.3271244e+20
  Cuerpo 2: 398600400000000.0
  Cuerpo 3: 4900271059999.999


### Cálculo de aceleraciones netas

Utilicemos la función `aceleraciones_n_cuerpos` para calcular la aceleración neta de cada uno de los tres cuerpos (Sol, Tierra, Luna) debido a la influencia gravitacional de los otros dos.


In [ ]:
a_netas = aceleraciones_n_cuerpos(r, mu)

print("Aceleraciones netas (Sol, Tierra, Luna) (km/s^2):")
for i, acc in enumerate(a_netas):
    print(f"  Cuerpo {i+1}: {acc}")

Aceleraciones netas (Sol, Tierra, Luna) (km/s^2):
  Cuerpo 1: [-1.59770341e-08  9.23204156e-09 -4.64715972e-13]
  Cuerpo 2: [ 5.28800509e-03 -3.04302248e-03  6.97077936e-07]
  Cuerpo 3: [ 2.56113152e-03 -2.50124588e-03 -4.41163256e-05]


## Cálculo de fuerzas netas

Multiplicaremos las aceleraciones netas de cada cuerpo por su respectiva masa para obtener las fuerzas gravitacionales netas actuando sobre el Sol, la Tierra y la Luna.


Definamos una lista de masas para el Sol, la Tierra y la Luna en el orden correcto para que se corresponda con la matriz `a_netas`. Luego, iteraremos sobre las masas y las aceleraciones netas para calcular las fuerzas netas y almacenarlas en `F_netas`.


In [ ]:
masses = [m_sol, m_tierra, m_luna]

F_netas = []
for i in range(len(masses)):
    F_netas.append(masses[i] * a_netas[i])

print("Fuerzas netas (Sol, Tierra, Luna) (N):")
body_names = ["Sol", "Tierra", "Luna"]
for i, force in enumerate(F_netas):
    print(f"  Fuerza neta sobre el {body_names[i]}: {force}")

Fuerzas netas (Sol, Tierra, Luna) (N):
  Fuerza neta sobre el Sol: [-3.17688924e+22  1.83570826e+22 -9.24045825e+17]
  Fuerza neta sobre el Tierra: [ 3.15808541e+22 -1.81734411e+22  4.16306645e+18]
  Fuerza neta sobre el Luna: [ 1.88038276e+20 -1.83641472e+20 -3.23902063e+18]


## Visualización del Sistema Sol-Tierra-Luna

¡Genial! Ahora que tengo tanta información, se me ocurre que puedo crear una visualización de la disposición del sistema Sol - Tierra - Luna para la fecha y época que hemos venido trabajando.
Para crear un gráfico bien chimbita, emplearé `plotly.graph_objects`

In [ ]:
!pip install plotly

In [ ]:
import plotly.graph_objects as go

# Extraer coordenadas x, y, z para cada cuerpo
x_S, y_S, z_S = r_S
x_T, y_T, z_T = r_T
x_L, y_L, z_L = r_L

# Crear la figura
fig = go.Figure()

# Añadir el Sol
fig.add_trace(go.Scatter3d(
    x=[x_S], y=[y_S], z=[z_S],
    mode='markers',
    marker=dict(size=10, color='gold'),
    name='Sol'
))

# Añadir la Tierra
fig.add_trace(go.Scatter3d(
    x=[x_T], y=[y_T], z=[z_T],
    mode='markers',
    marker=dict(size=5, color='blue'),
    name='Tierra'
))

# Añadir la Luna
fig.add_trace(go.Scatter3d(
    x=[x_L], y=[y_L], z=[z_L],
    mode='markers',
    marker=dict(size=3, color='silver'),
    name='Luna'
))

# Conectar Sol-Tierra
fig.add_trace(go.Scatter3d(
    x=[x_S, x_T], y=[y_S, y_T], z=[z_S, z_T],
    mode='lines',
    line=dict(color='gray', width=2, dash='dash'),
    name='Sol-Tierra'
))

# Conectar Tierra-Luna
fig.add_trace(go.Scatter3d(
    x=[x_T, x_L], y=[y_T, y_L], z=[z_T, z_L],
    mode='lines',
    line=dict(color='lightgray', width=1, dash='dot'),
    name='Tierra-Luna'
))

# Actualizar layout de la figura para fondo negro y texto blanco
fig.update_layout(
    title=dict(
        text=f'Disposición del Sistema Sol-Tierra-Luna el {epoch} (respecto al SSB)',
        font=dict(color='white') # Título en blanco
    ),
    scene=dict(
        xaxis=dict(title='X (km)',  backgroundcolor="black", gridcolor="gray", zerolinecolor="gray", showbackground=True, tickfont=dict(color='white'), titlefont=dict(color='white')),
        yaxis=dict(title='Y (km)',  backgroundcolor="black", gridcolor="gray", zerolinecolor="gray", showbackground=True, tickfont=dict(color='white'), titlefont=dict(color='white')),
        zaxis=dict(title='Z (km)',  backgroundcolor="black", gridcolor="gray", zerolinecolor="gray", showbackground=True, tickfont=dict(color='white'), titlefont=dict(color='white')),
        aspectmode='data' # Mantener la proporción real de los ejes
    ),
    paper_bgcolor='black', # Fondo del papel en negro
    plot_bgcolor='black'   # Fondo del gráfico en negro
)

fig.show()


> ¡Estoy emocionada por crear ya mismo una generalización para N cuerpos!, pero es casi 1am y el que trasnocha y madruga... bosteza dos veces. Descanso tranquila y doy cierre a los ejercicios de mi primera clase de Mecánica Celeste, con la seguridad de que me depara una clase bastante cercana donde Z, ya nos pondrá a desarrollar el ejercicio de los N cuerpos (incluso, probablemente todo el curso gire en torno al problema).

